### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by kamserv45** [redrbrt/sepomex-zip-codes#1]
Perdóname, estoy usando el traductor de Google. ¿Le importaría agregar un archivo de licencia? Si está permitido, me gustaría usar estos datos, pero no puedo, ya que la licencia predeterminada de GitHub lo prohíbe. Gracias.

**Comment by redrbrt** [comment]
> Perdóname, estoy usando el traductor de Google. ¿Le importaría agregar un archivo de licencia? Si está permitido, me gustaría usar estos datos, pero no puedo, ya que la licencia predeterminada de GitHub lo prohíbe. Gracias.

Done!
I'm no longer maintenance this data, however those records can be found fresh and up to date for free here:
https://www.correosdemexico.gob.mx/SSLServicios/ConsultaCP/CodigoPostal_Exportar.aspx

Or pricing by third party distributor:
https://copomex.com/#pricing-section
